git clone https://github.com/Valloric/YouCompleteMe.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/bling/vim-airline
git clone https://github.com/vim-airline/vim-airline-themes
git clone https://github.com/bling/vim-bufferline.git
git clone git://github.com/vhdirk/vim-cmake.git
git clone https://github.com/kchmck/vim-coffee-script.git
git clone https://github.com/flazz/vim-colorschemes.git
git clone https://github.com/tpope/vim-commentary.git
git clone https://github.com/Lokaltog/vim-easymotion.git
git clone https://github.com/dag/vim-fish.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/digitaltoad/vim-jade.git
git clone https://github.com/pangloss/vim-javascript.git
git clone git://github.com/tpope/vim-repeat.git
git clone git://github.com/tpope/vim-sensible.git
git clone git://github.com/tpope/vim-vinegar.git
